/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * MTL Park Map API
 * OpenAPI spec version: 0.1.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AddressLocation,
  AddressLocationParams,
  HTTPValidationError,
  PaidSpotsParams,
  ParkingSignsParams,
  SignCollection,
  SpotCollection
} from './model';

const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type parkingSignsResponse200 = {
  data: SignCollection
  status: 200
}

export type parkingSignsResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type parkingSignsResponseSuccess = (parkingSignsResponse200) & {
  headers: Headers;
};
export type parkingSignsResponseError = (parkingSignsResponse422) & {
  headers: Headers;
};

export type parkingSignsResponse = (parkingSignsResponseSuccess | parkingSignsResponseError)

export const getParkingSignsUrl = (params: ParkingSignsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    const explodeParameters = ["categories"];

    if (Array.isArray(value) && explodeParameters.includes(key)) {
      value.forEach((v) => {
        normalizedParams.append(key, v === null ? 'null' : String(v));
      });
      return;
    }

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/parking-signs?${stringifiedParams}` : `/api/parking-signs`
}

/**
 * @summary Parking Signs
 */
export const parkingSigns = async (params: ParkingSignsParams, options?: RequestInit): Promise<parkingSignsResponse> => {

  const res = await fetch(getParkingSignsUrl(params),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: parkingSignsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as parkingSignsResponse
}





export const getParkingSignsQueryKey = (params?: ParkingSignsParams,) => {
    return [
    `/api/parking-signs`, ...(params ? [params] : [])
    ] as const;
    }


export const getParkingSignsQueryOptions = <TData = Awaited<ReturnType<typeof parkingSigns>>, TError = HTTPValidationError>(params: ParkingSignsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof parkingSigns>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getParkingSignsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof parkingSigns>>> = ({ signal }) => parkingSigns(params, { signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof parkingSigns>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ParkingSignsQueryResult = NonNullable<Awaited<ReturnType<typeof parkingSigns>>>
export type ParkingSignsQueryError = HTTPValidationError


export function useParkingSigns<TData = Awaited<ReturnType<typeof parkingSigns>>, TError = HTTPValidationError>(
 params: ParkingSignsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof parkingSigns>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof parkingSigns>>,
          TError,
          Awaited<ReturnType<typeof parkingSigns>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useParkingSigns<TData = Awaited<ReturnType<typeof parkingSigns>>, TError = HTTPValidationError>(
 params: ParkingSignsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof parkingSigns>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof parkingSigns>>,
          TError,
          Awaited<ReturnType<typeof parkingSigns>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useParkingSigns<TData = Awaited<ReturnType<typeof parkingSigns>>, TError = HTTPValidationError>(
 params: ParkingSignsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof parkingSigns>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Parking Signs
 */

export function useParkingSigns<TData = Awaited<ReturnType<typeof parkingSigns>>, TError = HTTPValidationError>(
 params: ParkingSignsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof parkingSigns>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getParkingSignsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







export type paidSpotsResponse200 = {
  data: SpotCollection
  status: 200
}

export type paidSpotsResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type paidSpotsResponseSuccess = (paidSpotsResponse200) & {
  headers: Headers;
};
export type paidSpotsResponseError = (paidSpotsResponse422) & {
  headers: Headers;
};

export type paidSpotsResponse = (paidSpotsResponseSuccess | paidSpotsResponseError)

export const getPaidSpotsUrl = (params: PaidSpotsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/paid-spots?${stringifiedParams}` : `/api/paid-spots`
}

/**
 * @summary Paid Spots
 */
export const paidSpots = async (params: PaidSpotsParams, options?: RequestInit): Promise<paidSpotsResponse> => {

  const res = await fetch(getPaidSpotsUrl(params),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: paidSpotsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as paidSpotsResponse
}





export const getPaidSpotsQueryKey = (params?: PaidSpotsParams,) => {
    return [
    `/api/paid-spots`, ...(params ? [params] : [])
    ] as const;
    }


export const getPaidSpotsQueryOptions = <TData = Awaited<ReturnType<typeof paidSpots>>, TError = HTTPValidationError>(params: PaidSpotsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof paidSpots>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPaidSpotsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof paidSpots>>> = ({ signal }) => paidSpots(params, { signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof paidSpots>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PaidSpotsQueryResult = NonNullable<Awaited<ReturnType<typeof paidSpots>>>
export type PaidSpotsQueryError = HTTPValidationError


export function usePaidSpots<TData = Awaited<ReturnType<typeof paidSpots>>, TError = HTTPValidationError>(
 params: PaidSpotsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof paidSpots>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof paidSpots>>,
          TError,
          Awaited<ReturnType<typeof paidSpots>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePaidSpots<TData = Awaited<ReturnType<typeof paidSpots>>, TError = HTTPValidationError>(
 params: PaidSpotsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof paidSpots>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof paidSpots>>,
          TError,
          Awaited<ReturnType<typeof paidSpots>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePaidSpots<TData = Awaited<ReturnType<typeof paidSpots>>, TError = HTTPValidationError>(
 params: PaidSpotsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof paidSpots>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Paid Spots
 */

export function usePaidSpots<TData = Awaited<ReturnType<typeof paidSpots>>, TError = HTTPValidationError>(
 params: PaidSpotsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof paidSpots>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getPaidSpotsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







export type addressLocationResponse200 = {
  data: AddressLocation
  status: 200
}

export type addressLocationResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type addressLocationResponseSuccess = (addressLocationResponse200) & {
  headers: Headers;
};
export type addressLocationResponseError = (addressLocationResponse422) & {
  headers: Headers;
};

export type addressLocationResponse = (addressLocationResponseSuccess | addressLocationResponseError)

export const getAddressLocationUrl = (params: AddressLocationParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/address-location?${stringifiedParams}` : `/api/address-location`
}

/**
 * @summary Address Location
 */
export const addressLocation = async (params: AddressLocationParams, options?: RequestInit): Promise<addressLocationResponse> => {

  const res = await fetch(getAddressLocationUrl(params),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: addressLocationResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as addressLocationResponse
}





export const getAddressLocationQueryKey = (params?: AddressLocationParams,) => {
    return [
    `/api/address-location`, ...(params ? [params] : [])
    ] as const;
    }


export const getAddressLocationQueryOptions = <TData = Awaited<ReturnType<typeof addressLocation>>, TError = HTTPValidationError>(params: AddressLocationParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof addressLocation>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAddressLocationQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof addressLocation>>> = ({ signal }) => addressLocation(params, { signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof addressLocation>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AddressLocationQueryResult = NonNullable<Awaited<ReturnType<typeof addressLocation>>>
export type AddressLocationQueryError = HTTPValidationError


export function useAddressLocation<TData = Awaited<ReturnType<typeof addressLocation>>, TError = HTTPValidationError>(
 params: AddressLocationParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof addressLocation>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof addressLocation>>,
          TError,
          Awaited<ReturnType<typeof addressLocation>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAddressLocation<TData = Awaited<ReturnType<typeof addressLocation>>, TError = HTTPValidationError>(
 params: AddressLocationParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof addressLocation>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof addressLocation>>,
          TError,
          Awaited<ReturnType<typeof addressLocation>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAddressLocation<TData = Awaited<ReturnType<typeof addressLocation>>, TError = HTTPValidationError>(
 params: AddressLocationParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof addressLocation>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Address Location
 */

export function useAddressLocation<TData = Awaited<ReturnType<typeof addressLocation>>, TError = HTTPValidationError>(
 params: AddressLocationParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof addressLocation>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAddressLocationQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}
