/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * MTL Park Map API
 * OpenAPI spec version: 0.1.0
 */

export type PaidSpotsParams = {
hour_start?: number | null;
hour_end?: number | null;
day_start?: number | null;
day_end?: number | null;
month_start?: number | null;
month_end?: number | null;
min_lon: number;
min_lat: number;
max_lon: number;
max_lat: number;
};
