/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * MTL Park Map API
 * OpenAPI spec version: 0.1.0
 */
import type { SignFeature } from './signFeature';

export interface SignCollection {
  type?: 'FeatureCollection';
  features: SignFeature[];
}
