/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * MTL Park Map API
 * OpenAPI spec version: 0.1.0
 */
import type { SignCategory } from './signCategory';

export interface SignProperties {
  sign_id: number;
  category: SignCategory;
  is_reserved: boolean;
  arrondissement?: string | null;
  description: string;
}
