/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * MTL Park Map API
 * OpenAPI spec version: 0.1.0
 */

export type SignCategory = typeof SignCategory[keyof typeof SignCategory];


export const SignCategory = {
  permitted: 'permitted',
  prohibited: 'prohibited',
  other: 'other',
} as const;
