/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * MTL Park Map API
 * OpenAPI spec version: 0.1.0
 */
import type { PointGeometry } from './pointGeometry';
import type { SignProperties } from './signProperties';

export interface SignFeature {
  type?: 'Feature';
  geometry: PointGeometry;
  properties: SignProperties;
}
