/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * MTL Park Map API
 * OpenAPI spec version: 0.1.0
 */
import type { PointGeometry } from './pointGeometry';
import type { SpotProperties } from './spotProperties';

export interface SpotFeature {
  type?: 'Feature';
  geometry: PointGeometry;
  properties: SpotProperties;
}
