/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * MTL Park Map API
 * OpenAPI spec version: 0.1.0
 */

export interface SpotProperties {
  place_id: string;
  is_currently_free: boolean;
  tariff_hourly?: number | null;
  spot_type?: string | null;
  street?: string | null;
  periods?: string[];
}
