/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * MTL Park Map API
 * OpenAPI spec version: 0.1.0
 */
import type { SpotFeature } from './spotFeature';

export interface SpotCollection {
  type?: 'FeatureCollection';
  features: SpotFeature[];
}
